const phonemes = 
  {
    'n': 'cog',
    'm': 'nop',
    'l': 'pul',
    'e': 'thru',
    's': 'sin',
    't': 'choose',
    'a': 'top',
    'b': '',
    'c': '',
    'd': '',
    'f': '',
    'g': '',
    'h': '',
    'i': 'look',
    'j': 'poke',
    'k': 'stop',
    'o': 'open',
    'p': 'push',
    'q': 'slow',
    'r': 'turn',
    'u': 'reverse',
    'v': 'reflect',
    'w': 'copy',
    'x': 'grow',
    'y': 'split',
    'z': 'oppose'
  }

